name = "QuadProg"
version = "0.1.0"
license = "license"
maintainer = "jean-christophe.loiseau@ensam.eu"
author = "Jean-Christophe Loiseau"
copyright = "Copyright 2020 Jane Doe"
#description = "A short project summary in plain text"
#categories = ["fortran", "graphics"]
keywords = ["Convex optimization", "Quadratic Program"]
#homepage = "https://stdlib.fortran-lang.org"

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = true
source-form = "default"

[build]
auto-executables = true
auto-examples = true
auto-tests = true
module-naming = false # ???
link = ["blas", "lapack"]

[library]
source-dir="src"

[dev-dependencies]
test-drive.git = "https://github.com/nekStab/test-drive.git"

#----------------------------------------------------
#-----     Model Predictive Control example     -----
#----------------------------------------------------
[[example]]
name = "mpc"
source-dir = "example/mpc"

[[example]]
name = "compact_mpc"
source-dir = "example/compact_mpc"

#----------------------------------------------------
#-----     Markowitz Portoflio Optimization     -----
#----------------------------------------------------

[[example]]
name = "markowitz"
source-dir = "example/markowitz"

# #------------------------------------------------------
# #-----     Non-negative least-squares example     -----
# #------------------------------------------------------
# [[example]]
#
# name = "nnls"
# source-dir = "example/nnls"
