name: Setup Fortran Conda CI/CD

on:
  push:
    branches: [main, master, dev, cmake_build]

permissions:
  contents: write

jobs:

  # Run CMake build/tests across OS/compiler matrix
  test_cmake:
    name: ${{ matrix.os }}_${{ matrix.compiler }}_cmake
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gfortran
            compiler-version: 14.2.0
            flag-debug: "-Wno-external-argument-mismatch -coverage"
            extra-packages: "lcov, fypp"
          - os: ubuntu-latest
            compiler: ifx
            compiler-version: 2025.2.1
            extra-packages: "fypp"

    steps:
      - name: Setup Fortran
        uses: gha3mi/setup-fortran-conda@latest
        with:
          compiler: ${{ matrix.compiler }}
          compiler-version: ${{ matrix.compiler-version }}
          platform: ${{ matrix.os }}
          extra-packages: ${{ matrix.extra-packages }}

      - name: cmake test (debug)
        run: |
          cmake -S . -B build/debug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_Fortran_COMPILER=${{ matrix.compiler }}
          cmake --build build/debug
          ctest --test-dir build/debug --output-on-failure

      - name: cmake test (release)
        run: |
          cmake -S . -B build/release -DCMAKE_BUILD_TYPE=Release -DCMAKE_Fortran_COMPILER=${{ matrix.compiler }}
          cmake --build build/release
          ctest --test-dir build/release --output-on-failure
