name: ci
on: [push]

permissions:
  contents: write

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # GFotran compiler.
          - {os: ubuntu-latest, compiler: gfortran, compiler-version: 10, extra-packages: "pkg-config openblas"}
          - {os: ubuntu-latest, compiler: gfortran, compiler-version: 11, extra-packages: "pkg-config openblas"}
          - {os: ubuntu-latest, compiler: gfortran, compiler-version: 12, extra-packages: "pkg-config openblas"}
          - {os: ubuntu-latest, compiler: gfortran, compiler-version: 13, extra-packages: "pkg-config openblas"}
          - {os: ubuntu-latest, compiler: gfortran, compiler-version: 14, extra-packages: "pkg-config openblas"}
          - {os: ubuntu-latest, compiler: gfortran, compiler-version: 15, extra-packages: "pkg-config openblas"}
          - {os: windows-latest, compiler: gfortran, compiler-version: 15, extra-packages: "pkg-config openblas"}
          - {os: macos-latest, compiler: gfortran, compiler-version: 15, extra-packages: "pkg-config openblas"}

          # Intel IFX.
          - {os: ubuntu-latest, compiler: ifx, extra-packages: "pkg-config mkl"}
          # - {os: windows-latest, compiler: ifx, extra-packages: "pkg-config mkl", fpm-version: "0.12.0"}  # Cannot find mkl_intel_lp64.lib

          # Other compilers.
          - {os: ubuntu-latest,  compiler: flang-new, extra-packages: "pkg-config openblas"}
          # - {os: ubuntu-latest,  compiler: nvfortran, extra-packages: "pkg-config openblas"}  # Error with assert_m package.

    steps:
      - name: Setup Fortran
        uses: gha3mi/setup-fortran-conda@latest
        with:
          platform: ${{ matrix.os }}
          compiler: ${{ matrix.compiler }}
          compiler-version: ${{ matrix.compiler-version }}
          extra-packages: ${{ matrix.extra-packages }}
          fpm-version: ${{ matrix.fpm-version }}

      - name: fpm test (debug)
        run: fpm test --compiler ${{ matrix.compiler }} ${{ matrix.fpm-options }} --verbose

      - name: Run example
        run: fpm run --compiler ${{ matrix.compiler }} --example
